# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Minute.tech' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Minute.tech
	pod 'Firebase/Core'
    pod 'Firebase/Storage'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
    
  target 'Minute.techTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Minute.techUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
